"""LLM judge: read each transcript and draft bug-report entries.

For every transcripts/transcript-NN.json, ask an OpenAI chat model to compare the conversation
against the scenario's goal + success criteria and surface concrete issues. Results are written
to BUG_REPORT.md (curate before submitting) and bug_findings.json.

Usage:  python scripts/analyze.py
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from openai import OpenAI  # noqa: E402

from app import config  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

JUDGE_SYSTEM = """\
You are a meticulous QA analyst reviewing a phone call between a PATIENT (a test bot) and a
medical clinic's AI RECEPTIONIST. You are evaluating the RECEPTIONIST, not the patient.

Find genuine bugs and quality issues. Prioritize useful, well-described problems over nitpicks.
Look specifically for:
- Hallucinated confirmations (e.g., confirming a booking/time it never verified).
- Booking on closed days / ignoring stated office hours; internal contradictions.
- Invented facts: insurance accepted, prices, policies, locations not actually known.
- Giving medical advice/diagnosis it should not give; missing safety hand-offs.
- Dropping one request in a multi-intent call; losing track of context.
- Broken turn-taking, talking over the caller, long dead air, or repetition (if visible).
- Failing the scenario's success criteria.

Ignore: punctuation, minor phrasing, the patient bot's own mistakes. Do NOT flag a date or
weekday as invalid unless it genuinely conflicts (e.g. a weekend when the clinic is closed) —
use the provided current date for reasoning, and don't speculate about dates you can't verify.

END-OF-CALL MARKER: a line like "Hello, you've reached the Pretty Good AI test line. Goodbye."
(or any mention of reaching the "Pretty Good AI test line") is an AUTOMATED marker that the test/
demo session has ended. It is NOT the clinic agent, NOT a real dropped call, and NOT a failed
transfer. Judge the agent ONLY on what it says BEFORE that marker. Do NOT raise findings about
the call "ending abruptly", a hand-off "not completing", or the caller "never reaching a live
representative" when those stem from this demo ending. (You MAY still assess whether the agent's
decision to transfer instead of handling the request itself was appropriate, based on what it
said before the marker.)

Return STRICT JSON:
{
  "findings": [
    {
      "bug": "one-line summary",
      "severity": "High|Medium|Low",
      "timecode": "m:ss from the transcript where it occurs, or 'n/a'",
      "details": "what happened and why it's a problem",
      "expected": "what the agent should have done"
    }
  ],
  "summary": "1-2 sentence overall assessment of this call"
}
If there are no real issues, return an empty findings list with a summary saying so.
"""


def transcript_to_text(data: dict) -> str:
    label = {"agent": "AGENT (PGAI)", "patient": "PATIENT (bot)"}
    lines = []
    for ln in data["lines"]:
        m, s = divmod(int(ln["t"]), 60)
        lines.append(f"[{m}:{s:02d}] {label.get(ln['role'], ln['role'])}: {ln['text']}")
    return "\n".join(lines)


def judge_call(client: OpenAI, data: dict) -> dict:
    user = (
        f"Current date (when the call was placed): {date.today():%A, %B %d, %Y}\n"
        f"Scenario {data['scenario_id']}: {data['scenario_title']}\n"
        f"Patient's goal: {data['goal']}\n"
        f"Success criteria: {data['success_criteria']}\n\n"
        f"TRANSCRIPT:\n{transcript_to_text(data)}"
    )
    resp = client.chat.completions.create(
        model=config.OPENAI_JUDGE_MODEL,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": JUDGE_SYSTEM},
            {"role": "user", "content": user},
        ],
    )
    return json.loads(resp.choices[0].message.content)


def main() -> None:
    config.require_env("OPENAI_API_KEY")
    client = OpenAI(api_key=config.OPENAI_API_KEY)

    files = sorted(config.TRANSCRIPTS_DIR.glob("transcript-*.json"))
    if not files:
        raise SystemExit("No transcripts found. Run scripts/run_batch.py first.")

    all_results = []
    md = ["# Bug Report (auto-drafted — curate before submitting)\n",
          "Generated by `scripts/analyze.py`. Keep the useful findings, drop the nitpicks.\n"]

    for f in files:
        data = json.loads(f.read_text())
        print(f"[analyze] judging {f.name} ...")
        try:
            result = judge_call(client, data)
        except Exception as exc:  # noqa: BLE001
            print(f"[analyze] failed on {f.name}: {exc}")
            continue
        result["call_index"] = data["call_index"]
        result["scenario_title"] = data["scenario_title"]
        all_results.append(result)

        md.append(f"\n## Call {data['call_index']:02d} — {data['scenario_title']}")
        md.append(f"_Transcript: transcript-{data['call_index']:02d}.txt_\n")
        md.append(f"**Summary:** {result.get('summary', '').strip()}\n")
        findings = result.get("findings", [])
        if not findings:
            md.append("_No notable issues found._\n")
        for fi in findings:
            md.append(
                f"- **Bug:** {fi.get('bug', '').strip()}  \n"
                f"  **Severity:** {fi.get('severity', 'n/a')} | "
                f"**At:** transcript-{data['call_index']:02d}.txt {fi.get('timecode', 'n/a')}  \n"
                f"  **Details:** {fi.get('details', '').strip()}  \n"
                f"  **Expected:** {fi.get('expected', '').strip()}"
            )

    (ROOT / "bug_findings.json").write_text(json.dumps(all_results, indent=2))
    (ROOT / "BUG_REPORT.md").write_text("\n".join(md) + "\n")
    print("[analyze] wrote BUG_REPORT.md and bug_findings.json")


if __name__ == "__main__":
    main()
